# Generated by Django 4.0.3 on 2022-03-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('car_type', models.CharField(max_length=25)),
                ('available', models.BooleanField(max_length=10)),
            ],
        ),
    ]
