# Generated by Django 4.0.3 on 2022-03-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='is_available',
        ),
    ]
