# Generated by Django 4.0.3 on 2022-03-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0003_remove_car_id_alter_car_license_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate_number',
            field=models.CharField(max_length=10),
        ),
    ]
