# Generated by Django 4.0.3 on 2022-03-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0004_car_car_id_alter_car_license_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('store_id', models.IntegerField()),
            ],
        ),
    ]
