# Generated by Django 4.0.3 on 2022-03-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0006_inventory_store_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(default=0)),
                ('car_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('employee_id', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.IntegerField(default=0)),
                ('car_id', models.IntegerField(default=0)),
            ],
        ),
    ]
