# Generated by Django 4.0.3 on 2022-03-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0007_customer_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='license_plate_number',
            new_name='license_plate',
        ),
    ]
