# Generated by Django 4.0.3 on 2022-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0008_rename_license_plate_number_car_license_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='count',
            new_name='sedan_count',
        ),
        migrations.AddField(
            model_name='inventory',
            name='suv_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='truck_count',
            field=models.IntegerField(default=0),
        ),
    ]
