# Generated by Django 4.0.3 on 2022-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0008_rename_license_plate_number_car_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='store_id',
            field=models.IntegerField(default=0),
        ),
    ]
