# Generated by Django 4.0.4 on 2022-04-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0009_car_store_id'),
        ('Kars4U_components', '0009_employee_currentlyworking'),
    ]

    operations = [
    ]
