# Generated by Django 4.0.2 on 2022-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kars4U_components', '0009_rename_count_inventory_sedan_count_and_more'),
        ('Kars4U_components', '0010_merge_20220430_1809'),
    ]

    operations = [
    ]
